language: python

addons:
  apt:
    packages:
      - ldap-utils
      - slapd

matrix:
  include:
    - python: 3.7
      env: TOXENV=py37-pytest
    - python: 3.7
      env: TOXENV=py37-lint
    - python: 3.7
      env: TOXENV=format-check
    - python: 3.5
      env: TOXENV=docs

install:
  - pip install tox

script:
  - tox
