language: python

addons:
  apt:
    packages:
      - ldap-utils
      - slapd

matrix:
  allow_failures:
    - env: TOXENV=py37-pytest
    - env: TOXENV=py37-lint
  include:
    - python: 2.7
      env: TOXENV=py27-pytest
    - python: 2.7
      env: TOXENV=py27-lint
    - python: 3.7
      env: TOXENV=py37-pytest
    - python: 3.7
      env: TOXENV=py37-lint
    - python: 3.7
      env: TOXENV=format-check
    - python: 3.5
      env: TOXENV=docs

install:
  - pip install tox

script:
  - tox
